http://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py

# What is PyTorch?

두개의 목표를 고려한 파이썬 기반의 과학 연산 패키지이다.

* GPU의 힘을 사용하기위해 NumPy를 대체함.
* 극강의 유연성과 속도를 제공하기위한 딥러닝 연구 플랫폼

# Getting Started

### Tensors

Tensor는 NumPy의 ndarray와 유사하다. 연산을 가속하기위해 GPU를 사용하는데 사용할 수 있다.

In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.Tensor(5, 3)
print(x)


 0.0000e+00  0.0000e+00  1.0874e-42
 0.0000e+00  7.0065e-45  0.0000e+00
-1.1026e+31  6.4039e-43  0.0000e+00
 0.0000e+00  2.7552e-40  6.4039e-43
-1.8363e+31  6.4039e-43  0.0000e+00
[torch.FloatTensor of size 5x3]



랜덤한 숫자로 초기화된 행렬을 만들어보자

In [3]:
x = torch.rand(5, 3)
print(x)


 0.1375  0.8001  0.3234
 0.2814  0.8914  0.3116
 0.8063  0.5714  0.7871
 0.2778  0.7117  0.3138
 0.5008  0.1345  0.9032
[torch.FloatTensor of size 5x3]



이 행렬의 사이즈를 얻어보자

In [4]:
print(x.size())

torch.Size([5, 3])


> 
**note**: torch.Size 는 사실 tuple이다. 그래서 모든 tuple연산을 지원한다.

### 연산

연산을 위한 여러개의 문법이 있다. 아래의 예시에서 덧셈연산을 살펴보자

덧셈 문법 1

In [5]:
y = torch.rand(5, 3)
print(x + y)


 0.6104  1.1870  0.8477
 0.4738  1.5923  0.9572
 1.1354  1.2874  1.4990
 0.7647  1.4857  0.5961
 1.3493  0.4094  1.3150
[torch.FloatTensor of size 5x3]



덧셈 문법 2.

In [6]:
print(torch.add(x, y))


 0.6104  1.1870  0.8477
 0.4738  1.5923  0.9572
 1.1354  1.2874  1.4990
 0.7647  1.4857  0.5961
 1.3493  0.4094  1.3150
[torch.FloatTensor of size 5x3]



덧셈 : 인자로 출력텐서를 제공

In [7]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)


 0.6104  1.1870  0.8477
 0.4738  1.5923  0.9572
 1.1354  1.2874  1.4990
 0.7647  1.4857  0.5961
 1.3493  0.4094  1.3150
[torch.FloatTensor of size 5x3]



덧셈: 즉시 처리

In [8]:
# add 와 다름. add_
y.add_(x)
print(y)


 0.6104  1.1870  0.8477
 0.4738  1.5923  0.9572
 1.1354  1.2874  1.4990
 0.7647  1.4857  0.5961
 1.3493  0.4094  1.3150
[torch.FloatTensor of size 5x3]



> 
텐서를 즉시 변화시키는 모든 연산들은 \_가 붙는다. 
예를들어, x.copy \_ (y), x.t\_() 는 x를 변화시킨다.

Numpy와 유사한 인덱싱을 사용가능하다!

In [9]:
print(x[:, 1]) # 모든 row에 대해 1번 인덱스 열을 출력(0,1,2...)


 0.8001
 0.8914
 0.5714
 0.7117
 0.1345
[torch.FloatTensor of size 5]



In [10]:
print(x[:, [0,1]]) # 모든 row에 대해 0, 1번째 column


 0.1375  0.8001
 0.2814  0.8914
 0.8063  0.5714
 0.2778  0.7117
 0.5008  0.1345
[torch.FloatTensor of size 5x2]



리사이징 : 만약 텐서를 resize/reshape 하길 원한다면 torch.view 를 써보길 바란다.

In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # 사이즈 -1은 다른 차원에서부터 유추한다는걸 의미한다.
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


이후에 읽어볼것:

    transposing, indexing, slicing, 수학 연산, 선형대수, 랜덤 넘버 등...100가지 이상의 텐서 연산을 보고싶다면 여길 참고해 보시라.
http://pytorch.org/docs/master/torch.html
    

### NumPy 연결고리

Torch의 tensor 객체 -> Numpy의 Array객체로 변환하는것, 반대의 경우 모두 쉽다.

Torch의 tensor와 Numpy의 array는 메모리 위치를 공유하기떄문에 하나가 바뀌면 모두 바뀐다.

### Torch Tensor -> Numpy Array

In [12]:
a = torch.ones(5)
print(a)


 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]



In [13]:
b = a.numpy()
print(b)
print(type(a))
print(type(b))

[1. 1. 1. 1. 1.]
<class 'torch.FloatTensor'>
<class 'numpy.ndarray'>


Numpy Array에서 어떻게 값이 바뀌는지 보시길..


In [14]:
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
[torch.FloatTensor of size 5]

[2. 2. 2. 2. 2.]


In [15]:
id(a) == id(b)

False

In [16]:
a.sub_(1)
print(a)
print(b)



 1
 1
 1
 1
 1
[torch.FloatTensor of size 5]

[1. 1. 1. 1. 1.]


### Numpy Array -> PyTorch Tensor

In [17]:
import numpy as np


In [18]:
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]

 2
 2
 2
 2
 2
[torch.DoubleTensor of size 5]



CharTensor를 제외한 모든 CPU 상의 텐서는 NumPy로 혹은 역으로 변환이 가능하다.

### CUDA 텐서

텐서는 .cuda라는 메소드를 통해 GPU로 옮겨갈수있다.

In [19]:
x = torch.ones([4, 4])
y = torch.eye(4)

In [20]:
import time

In [21]:
start = time.time()
for _ in range(1000000):
    x.add_(y)

print(time.time() - start)

0.4653322696685791


In [22]:
x = torch.ones([4, 4])
y = torch.eye(4)

In [23]:
start = time.time()
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    for _ in range(1000000):
        x.add_(y)

print(time.time() - start)

28.846625804901123
